vich_uploader:
    db_driver: orm

    mappings:
        projet:
            uri_prefix: /images/projet
            upload_destination: '%kernel.project_dir%/public/images/projet'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    
       # partenaire:
       #     uri_prefix: /images/partenaire
       #     upload_destination: '%kernel.project_dir%/public/images/partenaire'
       #
       #     inject_on_load: false
       #     delete_on_update: true
       #     delete_on_remove: true