<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH1BPzKm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH1BPzKm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH1BPzKm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH1BPzKm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerH1BPzKm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'H1BPzKm',
    'container.build_id' => '1d01ee4f',
    'container.build_time' => 1565206512,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH1BPzKm');
