<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE9PJI3I\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE9PJI3I/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE9PJI3I.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE9PJI3I\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerE9PJI3I\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'E9PJI3I',
    'container.build_id' => '79e93827',
    'container.build_time' => 1566071858,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE9PJI3I');
